import Database from 'better-sqlite3';
import { Farm, Commerce, Transaction, Worker, AttendanceLog, WorkerPayment, Client, ClientPurchase, DashboardStats } from '../types';
export declare function initDatabase(dbPath?: string): Database.Database;
export declare function getDb(): Database.Database;
export declare const dbService: {
    getDashboardStats(): DashboardStats;
    getFarms(): Farm[];
    addFarm(farm: Omit<Farm, "id">): Farm;
    updateFarm(farm: Farm): Farm;
    deleteFarm(id: number): boolean;
    getCommerces(): Commerce[];
    addCommerce(commerce: Omit<Commerce, "id">): Commerce;
    updateCommerce(commerce: Commerce): Commerce;
    deleteCommerce(id: number): boolean;
    getTransactions(): Transaction[];
    addTransaction(t: Omit<Transaction, "id">): Transaction;
    deleteTransaction(id: number): boolean;
    getWorkers(): Worker[];
    addWorker(worker: Omit<Worker, "id">): Worker;
    updateWorker(worker: Worker): Worker;
    deleteWorker(id: number): boolean;
    getAttendanceLogs(date?: string): AttendanceLog[];
    recordAttendance(log: Omit<AttendanceLog, "id">): AttendanceLog;
    addWorkerPayment(payment: Omit<WorkerPayment, "id">): WorkerPayment;
    getWorkerPayments(workerId?: number): WorkerPayment[];
    verifyKioskPin(pinCode: string): Worker | null;
    getClients(): Client[];
    addClient(client: Omit<Client, "id">): Client;
    updateClient(client: Client): Client;
    deleteClient(id: number): boolean;
    getClientPurchases(clientId: number): ClientPurchase[];
    addClientPurchase(purchase: Omit<ClientPurchase, "id">): ClientPurchase;
    payClientDebt(purchaseId: number, amount: number): boolean;
};
